name: example
description: Example Application using simple_json_persistence
publish_to: none

environment:
  sdk: ">=2.1.0 <3.0.0"
dependencies:
  logging_appenders:
    path: ../
dev_dependencies:
  pedantic: '>=1.5.0 <2.0.0'
