name: logging_appenders
description: Logging appenders for the dart logging package for print, file and remote (logz, loki).
version: 0.4.3+1
homepage: https://github.com/hpoul/dart_logging_appenders/

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta: '>=1.0.0 <2.0.0'
  logging: '>=1.0.0 <2.0.0'
  dio: '>=3.0.0 <4.0.0'
  intl: '>=0.15.0 <1.0.0'
  clock: '>=1.0.0 <2.0.0'

dev_dependencies:
  test: ">=1.5.0 <2.0.0"
  pedantic: '>=1.5.0 <2.0.0'
  mockito: '>=5.0.0-nullsafety.7 <6.0.0'
  fake_async: ^1.0.1
  path: '>=1.6.0 <2.0.0'
  build_runner: ^1.11.1

dependency_overrides:
  pedantic: ^1.8.0+1
  dio:
    git:
      url: https://github.com/harsimranmaan/dio.git
      ref: null-safety
      path: dio
